# Generated by Django 4.2.3 on 2023-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
