# Generated by Django 4.2.3 on 2023-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
